# training stuff
dataset_path: "/ad/eng/research/eng_research_cisl/jalido/sbrnet/data/training_data/dataset0"
train_split: 0.8
batch_size: 2
learning_rate: 0.001
epochs: 20000
model_save_path: "/projectnb/tianlabdl/jalido/sbrnet_proj/trained_models/"
backbone: "resnet"
resnet_channels: 48
weight_init: "kaiming_normal"
random_seed: 42
optimizer: "adam"
criterion_name: "bce_with_logits"
use_amp: False
lr_scheduler: "cosine_annealing"


# model stuff
num_gt_layers: 24
num_lf_views: 9
num_rfv_layers: 24
num_resblocks: 20