data_folder: "/projectnb/tianlabdl/jalido/sbrnet/data/training_data/dataset0/"
batch_size: 8
learning_rate: 0.001
epochs: 10
model_save_path: "/projectnb/tianlabdl/jalido/sbrnet/models/"
backbone: "resnet"
resnet_channels: 48
weight_initialization: "he_normal"